name: tcrpeg_env
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python
  - numpy
  - seaborn
  - matplotlib
  - faiss
  - tqdm
  - pandas
  - scikit-learn
  - scipy
  - snakemake
  - kneed
  - umap-learn
  - plotly
  - hdbscan
  - pip
  - pip:
      - torch >= 1.1.0
#todo add version numbers to dependencies
