name: tcrpeg_env
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python
  - numpy
  - seaborn
  - matplotlib
  - tqdm
  - torch
  - pandas
  - scikit-learn
  - snakemake
  - pip
#todo add version numbers to dependencies